services:
  autopcr:
    build:
      context: .
      dockerfile: Dockerfile
    image: autopcr:latest
    container_name: autopcr
    restart: unless-stopped
    volumes:
      - /opt/infra/stacks/app-autopcr/cache:/app/cache
      - /opt/infra/stacks/app-autopcr/log:/app/log
      - /opt/infra/stacks/app-autopcr/result:/app/result
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
